# -*- coding: utf-8 -*-
"""Dash DataTable - 2021 Big Data Cup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GR-w14PEAa64UfBIlmZYUXV27ikAMOrO
"""

pip install dash==1.20.0

import dash
import dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/bigdatacup/Big-Data-Cup-2021/main/hackathon_womens.csv')

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict('records'),
)

if __name__ == '__main__':
    app.run_server(debug=True)